--- #YAML:1.0
name:               Mail-Toaster
version:            5.11
abstract:           Mail::Toaster perl programs and modules
author:
    - Matt Simerson (matt@tnpi.net)
license:            bsd
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Date::Parse:       1
    DBI:               1
    Email::Valid:      0
    IO::Socket::SSL:   0
    Mail::Ezmlm:       0
    Net::DNS:          0.2
    Params::Validate:  0.7
    Test::Simple:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
